### ISSUE TITLE
Further use

### ISSUE THREAD

**Issue by Lejenk** [chithakumar13/fut-trade-enhancer#1]
No issue. Your work is amazing and I wish I even knew how to do 1% of what you know. I was just wondering whether you believe you would be able to create a way for the fifa transfers to only show good deal. For example at the moment it shows the good deals when you search for a certain player/card. And I was wondering if u think it’s possible to make it so you can only see these good deals for that one card. Or even only see good deals on every card in the game. So when you search transfers it gives you the best deals on any card

**Comment by suave123** [comment]
I would like to see the good deals on bids as well. Now it only show BIN good deals but it should check the current bid (or when the is no bid at all the min. bid) and compare that with the futbin price.
