### ISSUE TITLE
Fifa 22 Issues and possible improvement

### ISSUE THREAD

**Issue by Lukesxs** [chithakumar13/fut-trade-enhancer#10]
Improvement: (based on old Fut Enhancer) [Fut Enhancer](https://github.com/Mardaneus86/futwebapp-tampermonkey)
Add players Futbin prices to Squad Screen (also SBC)

Issue:
SBC import tool not pulling in, freezes on import

**Comment by suave123** [comment]
I can confirm these issues....

**Comment by headsh0t** [comment]
SBC import tool is working. you have to wait like 30 seconds for players to be added.

**Comment by Lukesxs** [comment]
It was fixed in latest update. Closed
