### ISSUE TITLE
Fifa 22 update for futbin sbc solutions

### ISSUE THREAD

**Issue by cnbrkc** [chithakumar13/fut-trade-enhancer#11]
@chithakumar13  I've been following you since your first app. I admire the work you do and the way you listen to us and help us. We thank you for everything.

Our request from you has been updated as 22 in the address section of the address bar with futbin fifa 22. I guess that's why the automatic sbc function doesn't work. I think;

https://www.futbin.com/**_22_**/squad/100004266/sbc

Since the part that says 22 is 21 in your system, it does not automatically fill in sbc. We would be very happy if you update it.

Thanks again for everything.

**Comment by chithakumar13** [comment]
fixed with latest release
