### ISSUE TITLE
[Feature Request] Transfer List value + futbin value

### ISSUE THREAD

**Issue by rocklyve** [chithakumar13/fut-trade-enhancer#12]
Hey,
I would love to see the following new feature:

In the transfer list, the total value of the list could be very useful :) 
Therefore the 
* futbin value
* min bid value
* buy now value
of the following lists could be added... (sold, unsold, available, active)

Furthermore, a total value of all the lists added could be added somewhere, so that we can see the total value of the transfer list.

**Comment by robertinho77** [comment]
I support this Feature Request. This would be very usefull
