### ISSUE TITLE
[Feature Request] Preview Pack Futbin Value

### ISSUE THREAD

**Issue by BScreen** [chithakumar13/fut-trade-enhancer#13]
Not sure if there's a way to access the preview pack popup in any way, but it would be incredible if you could add player prices to the preview pack. Individual prices would be great already, but showing the total pack value would be absolutely insane. That way you could judge whether a pack is worth buying or not in a matter of seconds.

Really appreciate all of your hard work and the fact you re-wrote the whole script. Incredible effort!
Cheers!

**Comment by Lukesxs** [comment]
Would also like this if possible, would be useful for player pick's as well later on in the year.

**Comment by chithakumar13** [comment]
Fixed in Latest Release
