### ISSUE TITLE
Futbin Block

### ISSUE THREAD

**Issue by suave123** [chithakumar13/fut-trade-enhancer#2]
Please think of circumventing the futbin block. When using this enhancer it usually takes about 15-30 mins when the webapp generates that many requests to futbin that futbin blocks your ip for 24 hrs.

**Comment by gsi-chao** [comment]
Futbin has repeatedly blocked my ip, 403 error message.

**Comment by chithakumar13** [comment]
As part of release 1.0.1, increased the cache time to avoid frequent FUTBIN calls, let see if it is sufficient
