### ISSUE TITLE
Suggestion : card price with the auto fill SBC

### ISSUE THREAD

**Issue by mimid2005** [chithakumar13/fut-trade-enhancer#28]
Hi,

I use the "Auto Fill" function to make some SBC. Is it possible to add in front of the cards, the futbin price? This will save a few minutes, because no need to go back and forth between the futbin site and the SBC page.

Thanks in advance if it is validated

**Comment by zivAnyvision** [comment]
Why not add the option just to auto-buy the cards for FUTbin price?

**Comment by chithakumar13** [comment]
will be done as part #50
