### ISSUE TITLE
[Feature Request] Page Number and Go to Page

### ISSUE THREAD

**Issue by ShahabSotouni** [chithakumar13/fut-trade-enhancer#32]
In the search result page add an indicator to show the page number and an option to go directly to a specific page.
For example, when trying to snipe players you may have to go 25 pages to reach the hour mark! 
TY!

**Comment by chithakumar13** [comment]
i already built a similar script for FIFA 21 [script](https://github.com/chithakumar13/Fifa21-PageJumper). But the thing it increases the chances of your account getting flagged for abnormal activity because in webapp normally you cannot go to say Page 10 with visting first 9 pages

**Comment by chithakumar13** [comment]
Not planning to implement , as this will result in account bans and people will start complaining about the script
