### ISSUE TITLE
[Feature Request] Futbin Price Download/Order

### ISSUE THREAD

**Issue by TheAlex9817** [chithakumar13/fut-trade-enhancer#36]
Is it possible to add futbin price to download csv?
Order club items by futbin price could be useful too.
If not, it could be helpful adding player id for searching in futbin with another script.
Thanks!

**Comment by chithakumar13** [comment]
Fixed with latest release

**Comment by TheAlex9817** [comment]
Hello, first of all, thanks very much for the function.
I found that prices are like "2,000", the csv reads it as 2 so one player which value is 200k is the same that one that is 200.
I think it will be solved only deleting the comma.
Thanks!
