### ISSUE TITLE
The results of items as consumables in the transfer market are not displayed.

### ISSUE THREAD

**Issue by gsi-chao** [chithakumar13/fut-trade-enhancer#4]
The results of items as consumables in the transfer market are not displayed.
It also happens with all the elements of the stadium
![image](https://user-images.githubusercontent.com/32143683/129957392-d55f0cf1-67b3-493f-b0ad-8957e747f0e2.png)

**Comment by gsi-chao** [comment]
![image](https://user-images.githubusercontent.com/32143683/129957707-61adb35a-76e7-46b8-b407-9526516e032b.png)

**Comment by chithakumar13** [comment]
Fixed as part of release 1.0.1

**Comment by gsi-chao** [comment]
thanks
