### ISSUE TITLE
feat: Enhancer Rating Setting Range 

### ISSUE THREAD

**Issue by sfxsalem** [chithakumar13/fut-trade-enhancer#41]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/chithakumar13/FUT-Auto-Buyer/issues) that already include this feature request, without success.

### Describe the Feature Request

If possible, i suggest to make the enhancer rating setting support intervals e.g. : 83-84...

### Describe the Use Case

This would be helpful with the AutoBuyer

**Comment by chithakumar13** [comment]
Implemented in the new release
