### ISSUE TITLE
Autocomplete sbc buys base card

### ISSUE THREAD

**Issue by sheshimateo** [chithakumar13/fut-trade-enhancer#42]
### Prerequisites

- [x] I have searched for [existing issues](https://github.com/chithakumar13/FUT-Auto-Buyer/issues) that already report this problem, without success.

### Script Version

1.1.5

### Platform

Webapp

### Current Behavior

After using the autofill sbc feature, if there are any special cards the bot buys their base card.

### Expected Behavior

The bot has to buy the related card version in sbc.

### Steps to Reproduce

1. Go to futbin and search for a completed sbc challenge where there is at least one special player.
2. Get the id on the url
3. Go in webapp into the related sbc and in the section autofill put the id and press button
4. After autofill completed, tap buy missing players
5. It's going to buy the base card for the special players.

**Comment by chithakumar13** [comment]
Fixed in latest release
