### ISSUE TITLE
feat: Card type in CSV export

### ISSUE THREAD

**Issue by markoo7** [chithakumar13/fut-trade-enhancer#43]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/chithakumar13/FUT-Auto-Buyer/issues) that already include this feature request, without success.

### Describe the Feature Request

The card type (bronze, silver, gold) and its rarity could be a nice enhancement to have inside the exported CSV file.

### Describe the Use Case

Club Items => Players => Download as CSV
Card Type column insertion
Rarity column to be renamed

**Comment by chithakumar13** [comment]
Implemented in the new release

**Comment by markoo7** [comment]
Thank you!
