### ISSUE TITLE
feat: Bronze Pack Opening

### ISSUE THREAD

**Issue by Wingyx98** [chithakumar13/fut-trade-enhancer#45]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/chithakumar13/FUT-Auto-Buyer/issues) that already include this feature request, without success.

### Describe the Feature Request

Are you able to add something that open bronze packs(or any packs) for you automatically with coins. You can get it to either add everything to your club or get it to store certain leagues to your club. You could get it to discard anything you dont want stored to the club.

### Describe the Use Case

With league SBCs out it would be benefical to be able to open loads off bronze packs for you to fill your club and make good profit. Bronze pack method is really good. This would help so much but im not sure if this would be possible to do

**Comment by chithakumar13** [comment]
Added in new release

**Comment by markoo7** [comment]
Hello, @chithakumar13 !
I have tested the new release with this new Auto-Opening feature!
It works great, you did a nice job and I saw that you even took into account my previous suggestions, which is fabulous!

Now, I don't wanna pull the string too much :D but if you will ever have some extra time to check again this area of code, some additional nice to have details which could bring a lot of positive outcome (that I missed in the first place) would be:

1. break the "non-players" category into 3 sub-categories (A. managers; B. contracts of any kind; C. all the rest)
More specific:
- we wanna keep the managers (some of them are really valuable)
- we wanna keep all the contracts (we use them for our team, they are really useful)
- we wanna quick-sell all the remaining useless stuff

2. break the "duplicates" category into 3 sub-categories (A. players; B. managers; C. all the rest)
More specific:
- if we have duplicate players (they are valuable, we don't wanna lose them by quick selling them) => move to transfer list
- if we have duplicate managers (they are valuable, we don't wanna lose them by quick selling them) => move to transfer list
- if we have duplicates of any other item => it is safe to quick sell them

If we would have this, it would really be the whole menu. :)
But I guess this is how humans are, they always want more. :D

You did a good job anyway and until any updates (if any), I will just handle all the things manually afterwards.
Thank you for your efforts!

**Comment by markoo7** [comment]
Huh, you even handled the extra pack which appears in some of the initially bought store packs + the redeeming of the coins. This is just great! Nicely done, @chithakumar13 !

**Comment by VIP2022** [comment]
hi  @chithakumar13
THANKS for good job man.

after we opened bronze packs  and  do  upgrade for...(NON )...( league SBC)   for bronze players +silver  players +gold players  ==  we gona have 100s of (in)( my packs)

so we need  to open all these packs only  ...  if we have it Duplicate  not tradable  sell it for zero..... if ....  Duplicate and tradable  send it to transfer market

for

1/  two silver players pack
2/ three common gold players
3/ two rare gold players pack

it will help us grinding

and bog thanks for helping poor people like us.
