### ISSUE TITLE
feat: Update FutBin price on SBC after navigating away from a previously filled SBC

### ISSUE THREAD

**Issue by flyinhawaiian5** [chithakumar13/fut-trade-enhancer#46]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/chithakumar13/FUT-Auto-Buyer/issues) that already include this feature request, without success.

### Describe the Feature Request

After navigating away from the SBC page after the FUTBIN import, it no longer shows the FUTBIN price. A button to refresh to see FUTBIN price would be nice especially when timing the right time to complete the SBC when prices fluctuate

### Describe the Use Case

Solves the issue of not knowing FUTBIN price after navigating away from the SBC screen

**Comment by chithakumar13** [comment]
Implemented in the new release
