### ISSUE TITLE
Unsupported Browser message in Google Chrome

### ISSUE THREAD

**Issue by uebmaster** [chithakumar13/fut-trade-enhancer#52]
I think that EA recognize the script or tampermonkey and is blocking the webapp cause in firefox i can open the webapp without problems.

What do you think?

![image](https://user-images.githubusercontent.com/5565506/144139947-7edc3cf6-5d01-4ef1-82f5-2ba021da4470.png)

**Comment by chithakumar13** [comment]
Doesnt seems to be related to the script
