### ISSUE TITLE
bug: autobuyer buy players in the work area, not only the need it in the squad

### ISSUE THREAD

**Issue by uebmaster** [chithakumar13/fut-trade-enhancer#56]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/chithakumar13/FUT-Auto-Buyer/issues) that already report this problem, without success.

### Script Version

1.1.8

### Platform

Webapp

### Current Behavior

i've tried to buy only 3 players from the squad  with the "buy missing players" feature and i had 2 players in the work area, but when i've selected the 3 players to buy, the script also has bought the 2 players in the work area.

### Expected Behavior

that the "buy missing players" feature just try to buy the players selected and ignore the players in the work area from the SBC.

### Steps to Reproduce

1. use autofill sbc feature
2. place any missing squad player in the work area and in the empty space put one of your club.
3. try to buy with the buy missing player feature the missing players in the squad.

**Comment by chithakumar13** [comment]
Fixed in new release
