### ISSUE TITLE
bug: SBC Autofill not working

### ISSUE THREAD

**Issue by dpearson2699** [chithakumar13/fut-trade-enhancer#58]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/chithakumar13/FUT-Auto-Buyer/issues) that already report this problem, without success.

### Script Version

1.1.9

### Platform

Webapp

### Current Behavior

After entering in the Futbin SBC ID it fills the squad with the correct players, but in the incorrect position.

### Expected Behavior

To fill the squad with the players in the correct position listed in the community SBC solution

### Steps to Reproduce

Specifically, this ID for the Winter Wildcards Challenge does not fill correctly: 100138449

**Comment by chithakumar13** [comment]
Fixed in new release

**Comment by dpearson2699** [comment]
> ### Prerequisites
> * [x]  I have searched for [existing issues](https://github.com/chithakumar13/FUT-Auto-Buyer/issues) that already report this problem, without success.
> 
> ### Script Version
> 1.1.9
> 
> ### Platform
> Webapp
> 
> ### Current Behavior
> After entering in the Futbin SBC ID it fills the squad with the correct players, but in the incorrect position.
> 
> ### Expected Behavior
> To fill the squad with the players in the correct position listed in the community SBC solution
> 
> ### Steps to Reproduce
> Specifically, this ID for the Winter Wildcards Challenge does not fill correctly: 100138449
> 
> ### Additional Information
> _No response_

This is unfortunately not fixed in the new release. For example the SBC Super-Sub using the futbin id of: 100144622 fills out the SBC in the fut web app like this
<img width="945" alt="image" src="https://user-images.githubusercontent.com/32114370/147836138-3b71a9ef-f479-4650-90a9-454d908b0ea7.png">

when it should fill out the players like this
<img width="660" alt="image" src="https://user-images.githubusercontent.com/32114370/147836168-a785c1e7-44ef-4b90-8a73-dc0b60693ed8.png">
