### ISSUE TITLE
bug: Transfertarget list top result unselectable

### ISSUE THREAD

**Issue by suave123** [chithakumar13/fut-trade-enhancer#59]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/chithakumar13/FUT-Auto-Buyer/issues) that already report this problem, without success.

### Script Version

1.1.9

### Platform

Webapp

### Current Behavior

when bidding on transfermarket items manually it is impossible to select the top item in the transfer target, it seems selected but it is not selected. Also won items have incorrect values so sometime you cant relist them. All is being fixed when going back to main menu and back to transfer targets.

### Expected Behavior

all targets should be able to be selected

### Steps to Reproduce

bid on multiple items and wait for people to rebid and then the problems start.

**Comment by chithakumar13** [comment]
This seems to be EA bug
