### ISSUE TITLE
bug: App hangs when fetching FUTBIN data with invalid SBC ID

### ISSUE THREAD

**Issue by zentby** [chithakumar13/fut-trade-enhancer#61]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/chithakumar13/FUT-Auto-Buyer/issues) that already report this problem, without success.

### Script Version

1.1.9

### Platform

Webapp

### Current Behavior

When putting SBC id accidentally with non-digital numbers, the "auto fill" button still clickable but it then hangs the app there  for a long time. 

### Expected Behavior

The SBC ID should be validated before continue.
If the futbin squad could not be found, it should be failed early (stop retrying and return).

### Steps to Reproduce

Open any SBC, type "abc" to the SBC id. Click "auto fill"

**Comment by chithakumar13** [comment]
Fixed
