### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by ataberkcemunal** [chithakumar13/fut-trade-enhancer#66]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/chithakumar13/FUT-Auto-Buyer/issues) that already report this problem, without success.

### Script Version

1.2.2

### Platform

Webapp

### Current Behavior

In SBCs, cards are sliding down and covering the chemistry ratings of the player so it is not possible to see the chemistry of the player in that position.
![image](https://user-images.githubusercontent.com/79286581/163330121-e91cb59b-81ed-4400-b8c4-e674d2c0178d.png)

### Expected Behavior

To be able to see the chemistry ratings of the players in SBCs.

### Steps to Reproduce

...

**Comment by chithakumar13** [comment]
Fixed in [1.2.0](https://github.com/chithakumar13/fut-trade-enhancer/releases/tag/1.2.0) release
