### ISSUE TITLE
bug:  Search by name doesn't work on sbc/squad page

### ISSUE THREAD

**Issue by flamingmoon** [chithakumar13/fut-trade-enhancer#68]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/chithakumar13/FUT-Auto-Buyer/issues) that already report this problem, without success.

### Script Version

@version     1.2.1

### Platform

Webapp

### Current Behavior

add player on sbc/squad page,than search by player name doesn't work,it will list all players.
ver1.1.9 is ok.

### Expected Behavior

fix it plz

### Steps to Reproduce
it's a gif,you need 2 click it. ^_^
<a href="https://ibb.co/hL1BW9H"><img src="https://i.ibb.co/34YpNdW/123.gif" alt="123" border="0"></a>

**Comment by chithakumar13** [comment]
Fixed in [1.2.1](https://github.com/chithakumar13/fut-trade-enhancer/releases/tag/1.2.1) release

**Comment by flamingmoon** [comment]
> 

thx
