### ISSUE TITLE
FUTBIN blocked

### ISSUE THREAD

**Issue by rafaelsaidbc** [chithakumar13/fut-trade-enhancer#7]
The FUTBIN prices disappeared, I tried to access the FUTBIN site and found that my access was blocked due to excessive requests.

**Comment by rafaelsaidbc** [comment]
The message I receveid when try access the site:
Error - 403. Your client does not have permission to access this page at this time. Contact us on support@futbin.com

**Comment by suave123** [comment]
pls update to the latest version, I havent had any bans since...

**Comment by chithakumar13** [comment]
@suave123 , Thanks for the input, Closing this issue
@rafaelsaidbc , Feel free to reopen if the issue persists
